<?php

namespace OC\PlatformBundle\Repository;

/**
 * ApplicationPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationPostRepository extends \Doctrine\ORM\EntityRepository
{
}
