<?php

namespace OC\PlatformBundle\Repository;

/**
 * CategoryPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryPostRepository extends \Doctrine\ORM\EntityRepository
{
}
