<?php

namespace OC\PlatformBundle\Repository;

/**
 * ImagePostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagePostRepository extends \Doctrine\ORM\EntityRepository
{
}
