<?php

namespace OC\PlatformBundle\Repository;

/**
 * PostProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostProduitsRepository extends \Doctrine\ORM\EntityRepository
{
}
